resource_group_name  = "koalatech-week08-rg"
location             = "australiaeast"
acr_name             = "koalatech08acr7785"
storage_account_name = "koalatechweek08st7785"
aks_cluster_name     = "koalatech-week08-aks"